### ISSUE TITLE
Motherboard is burned after running the code

### ISSUE THREAD

**Issue by aymansalama** [hgrif/wiki-word2vec#1]
i executed the procedure on dell tower 8 core, 16 G ram and the motherboard is burned. i am not sure the hardware had a problem or the code. any idea?

**Comment by hgrif** [comment]
Unlikely that it's the code per se. The standard settings do intensively use all cores expect one, but heavy CPU usage shouldn't burn your motherboard. So it more seems like a hardware issue.

**Comment by aymansalama** [comment]
I was running on ubuntu 12. So ubuntu 12 might not have protection for over heating. I am not sure. I am waiting for the hardware diagnoses from out IT dept. However i ran the code on Google cloud now on Debian and seems fine so far. Another mistake, i think i ran double process. As i thought at some level that the first process died. So it could be ubuntu issue, or dou le process or hardware.

**Comment by aymansalama** [comment]
I will update this thread for reference after i get a solid feedback

**Comment by aymansalama** [comment]
Problem solved, it was power cable problem. the processing script overheat the cable and it was damage internally. although the power supply led was on. it was not enough to power the server. very odd but true.
