### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1426-142

### ISSUE THREAD

**Issue by rachhitgarg** [hgrif/wiki-word2vec#4]
return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1426-142
7: character maps to <undefined>

**Comment by hgrif** [comment]
Can you give some more details on what you're doing? Are you using Python 3?

**Comment by marinelligiovanna** [comment]
I had the same problem with portuguese. I've fixed converting my output file to utf-8 encoding and adding a try/except block:
``` 
with open(outp, mode='w', encoding='utf8') as output:
        for i, text in enumerate(wiki.get_texts()):
            # Note: if you're using Python 2, use:
            # output.write(" ".join(unicode(text)) + "\n")
            #output.write(" ".join(text) + "\n")
            try:
                output.write(bytes(' '.join(text), 'utf-8').decode('utf-8') + '\n')
            except Exception:
                pass
            if i > 0 and i % 10000 == 0:
                logger.info("Saved %s articles", i)
            n = i
```

**Comment by hgrif** [comment]
There was a small hint how to fix it for Python2: :)

```python
# Note: if you're using Python 2, use:
# output.write(" ".join(unicode(text)) + "\n")
```

I've now converted that hint to code and it seems to work for Portuguese. Let me know if you have any problems.
